# --- データセット関連 ---
train_csv: "csv/F002_train_exB.csv"         # 訓練用 CSV ファイル
valid_csv: "csv/F002_valid_exB.csv"         # 検証用 CSV ファイル
stats_tensor: "./stats.pt"       # 正規化の平均・分散などが保存されたTensor
sort_by_len: true
# --- データローダー設定 ---
batch_size: 8
num_workers: 4
map_location: "cpu"                    # または "cuda"（stats, .ptロード時）

# --- モデル構成 ---
input_dim_mel: 80
input_dim_pitch: 1
d_model: 512
nhead: 8
num_layers: 8
dim_ff: 1024
dropout: 0.2
use_f0: false                           # false で F0 系の層を無効化
nu: 0.3

# --- 損失関係 ---
diag_w: 10.0                            # attention対角制約の重み
ga_w: 10.0
ce_w: 1.0                              # token分類があればその重み

# --- 学習設定 ---
lr: 2.0e-4
weight_decay: 0.5

# --- Trainer 設定 ---
max_epochs: 200
gpus: 1                                # GPU数（CPUの場合は0）
precision: "16-mixed"
gradient_clip_val: 5.0
accumulate_grad_batches: 4

# --- 出力先 ---
work_dir: "/media/akio/hdd1/mel/models/free2"                    # Lightningの出力ルート
log_dir: "/media/akio/hdd1/mel/models/free2"                        # TensorBoard ログ保存先
ckpt_dir: "/media/akio/hdd1/mel/models/free2"                # チェックポイント保存先

